rootProject.name = 'com.gsshop.flutter_microsvc_util'

include 'com.twitter.sdk.android.core'
project(':com.twitter.sdk.android.core').projectDir = file('../android/twitter-core')
include 'com.twitter.sdk.android.tweetcomposer'
project(':com.twitter.sdk.android.tweetcomposer').projectDir = file('../android/tweeter-composer')
